using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SwitchcaseIzone
{
    internal class Program
    {
        static void Main(string[] args)
        {
            string oper;

            Console.WriteLine(" ***  *********************  *            ********************            ******                  ***  ****************");
            Console.WriteLine(" ***  ********************  ***        ***                     ***        *******                 ***  ****************");
            Console.WriteLine(" ***                  ***    *       **      IZ*ONE MEMBERS      **       *** ****                ***  ***             ");
            Console.WriteLine(" ***                 ***           **                              **     ***  ****               ***  ***             ");
            Console.WriteLine(" ***                ***            **     [1] - Jang Wonyoung      **     ***   ****              ***  ***             ");
            Console.WriteLine(" ***               ***            **      [2] - Miyawaki Sakura     **    ***    ****             ***  ***             ");
            Console.WriteLine(" ***              ***             **      [3] - Jo Yuri             **    ***     ****            ***  ***             ");
            Console.WriteLine(" ***             ***             **       [4] - Choi Yena            **   ***      ****           ***  ***             ");
            Console.WriteLine(" ***            ***              **       [5] - Ahn Yujin            **   ***       ****          ***  ****************");
            Console.WriteLine(" ***           ***               *        [6] - Yabuki Nako           *   ***        ****         ***  ****************");
            Console.WriteLine(" ***          ***                **       [7] - Kwon Eunbi           **   ***         ****        ***  ***             ");
            Console.WriteLine(" ***         ***                 **       [8] - Kang Hyewon          **   ***          ****       ***  ***             ");
            Console.WriteLine(" ***        ***                   **      [9] - Honda Hitomi        **    ***           ****      ***  ***             ");
            Console.WriteLine(" ***       ***                    **      [10] - Kim Chaewon        **    ***            ****     ***  ***             ");
            Console.WriteLine(" ***      ***                      **     [11] - Kim Minju         **     ***             ****    ***  ***             ");
            Console.WriteLine(" ***     ***                       **     [12] - Lee Chaeyeon      **     ***              ****   ***  ***             ");
            Console.WriteLine(" ***    ***                          **                           **      ***               ****  ***  ***             ");
            Console.WriteLine(" ***   *******************             ***                     ***        ***                **** ***  ****************");
            Console.WriteLine(" ***  ********************                ********************            ***                 *******  ****************");

            Console.WriteLine("                                                              ");
            Console.WriteLine("Eyes on Me! The moment we become one, everyone pays attention!");
            Console.WriteLine("Hello! We are Iz*One and you may now select your bias.");
            Console.Write("Please enter the number of your bias: ");
            oper = Console.ReadLine().ToUpper();

            switch (oper)
            {
                case "1":
                    Console.WriteLine("                                             ");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***             Jang Wonyoung             ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***  Stage Name: Wonyoung                 ***");
                    Console.WriteLine(" ***  Birthday: August 31, 2004            ***");
                    Console.WriteLine(" ***  Zodiac Sign: Virgo                   ***");
                    Console.WriteLine(" ***  Birthplace: Seoul, South Korea       ***");
                    Console.WriteLine(" ***  Height: 171 cm (5'7)                 ***");
                    Console.WriteLine(" ***  Weight: 47 kg (104 lbs)              ***");
                    Console.WriteLine(" ***  Blood Type: O                        ***");
                    Console.WriteLine(" ***  Position: Lead Dancer, Center        ***");
                    Console.WriteLine(" ***    Sub Vocalist, Sub Rapper, Maknae   ***");
                    Console.WriteLine(" ***  Produce 48 final ranking: 1          ***");
                    Console.WriteLine(" ***  Official Color: Pink                 ***");
                    Console.WriteLine(" ***  Likes: Mint Choco ice cream          ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    break;
                case "2":
                    Console.WriteLine("                                             ");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***            Miyawaki Sakura            ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***  Stage Name: Sakura                   ***");
                    Console.WriteLine(" ***  Birthday: March 19, 1998             ***");
                    Console.WriteLine(" ***  Zodiac Sign: Pisces                  ***");
                    Console.WriteLine(" ***  Birthplace: Kagoshima City, Japan    ***");
                    Console.WriteLine(" ***  Height: 163 cm (5'4)                 ***");
                    Console.WriteLine(" ***  Weight: 43 kg (94 lbs)               ***");
                    Console.WriteLine(" ***  Blood Type: A                        ***");
                    Console.WriteLine(" ***  Position: Sub Vocalist,              ***");
                    Console.WriteLine(" ***    Sub Rapper, Visual                 ***");
                    Console.WriteLine(" ***  Produce 48 final ranking: 2          ***");
                    Console.WriteLine(" ***  Official Color: Pastel Pink          ***");
                    Console.WriteLine(" ***  Likes: Red Velvet and Video games    ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    break;
                case "3":
                    Console.WriteLine("                                             ");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***              Jo Yuri                  ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***  Stage Name: Yuri                     ***");
                    Console.WriteLine(" ***  Birthday: October 22, 2001           ***");
                    Console.WriteLine(" ***  Zodiac Sign: Libra                   ***");
                    Console.WriteLine(" ***  Birthplace: Busan, South Korea       ***");
                    Console.WriteLine(" ***  Height: 163 cm (5'4)                 ***");
                    Console.WriteLine(" ***  Weight: 45 kg (99 lbs)               ***");
                    Console.WriteLine(" ***  Blood Type: AB                       ***");
                    Console.WriteLine(" ***  Position: Main Vocalist              ***");
                    Console.WriteLine(" ***  Produce 48 final ranking: 3          ***");
                    Console.WriteLine(" ***  Official Color: Orange               ***");
                    Console.WriteLine(" ***  Likes: Singing, playing instruments  ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    break;
                case "4":
                    Console.WriteLine("                                             ");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***              Choi Yena                ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***  Stage Name: Yena                     ***");
                    Console.WriteLine(" ***  Birthday: September 29, 1999         ***");
                    Console.WriteLine(" ***  Zodiac Sign: Libra                   ***");
                    Console.WriteLine(" ***  Birthplace: Seoul, South Korea       ***");
                    Console.WriteLine(" ***  Height: 162 cm (5'3)                 ***");
                    Console.WriteLine(" ***  Weight: 45 kg (99 lbs)               ***");
                    Console.WriteLine(" ***  Blood Type: A                        ***");
                    Console.WriteLine(" ***  Position: Main Rapper, Lead Dancer,  ***");
                    Console.WriteLine(" ***    Lead Vocalist                      ***");
                    Console.WriteLine(" ***  Produce 48 final ranking: 4          ***");
                    Console.WriteLine(" ***  Official Color: Yellow               ***");
                    Console.WriteLine(" ***  Likes: Strawberry/Choco ice cream    ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    break;
                case "5":
                    Console.WriteLine("                                             ");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***              Ahn Yujin                ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***  Stage Name: Yujin                    ***");
                    Console.WriteLine(" ***  Birthday: September 1, 2003          ***");
                    Console.WriteLine(" ***  Zodiac Sign: Virgo                   ***");
                    Console.WriteLine(" ***  Birthplace: Daejeon, South Korea     ***");
                    Console.WriteLine(" ***  Height: 172 cm (5'7.5)               ***");
                    Console.WriteLine(" ***  Weight: 48 kg (106 lbs)              ***");
                    Console.WriteLine(" ***  Blood Type: A                        ***");
                    Console.WriteLine(" ***  Position: Lead Vocalist, Lead Dancer ***");
                    Console.WriteLine(" ***  Produce 48 final ranking: 5          ***");
                    Console.WriteLine(" ***  Official Color: Blue                 ***");
                    Console.WriteLine(" ***  Likes: Green Tea ice cream           ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    break;
                case "6":
                    Console.WriteLine("                                             ");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***              Yabuki Nako              ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***  Stage Name: Nako                     ***");
                    Console.WriteLine(" ***  Birthday: June 18, 2001              ***");
                    Console.WriteLine(" ***  Zodiac Sign: Gemini                  ***");
                    Console.WriteLine(" ***  Birthplace: Tokyo, Japan             ***");
                    Console.WriteLine(" ***  Height: 150 cm (4'11)                ***");
                    Console.WriteLine(" ***  Weight: 40 kg (88 lbs)               ***");
                    Console.WriteLine(" ***  Blood Type: N/A                      ***");
                    Console.WriteLine(" ***  Position: Sub Vocalist               ***");
                    Console.WriteLine(" ***  Produce 48 final ranking: 6          ***");
                    Console.WriteLine(" ***  Official Color: Sky Blue             ***");
                    Console.WriteLine(" ***  Likes: Twice and Ice cream           ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    break;
                case "7":
                    Console.WriteLine("                                             ");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***              Kwon Eunbi               ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***  Stage Name: Eunbi                    ***");
                    Console.WriteLine(" ***  Birthday: September 27, 1995         ***");
                    Console.WriteLine(" ***  Zodiac Sign: Libra                   ***");
                    Console.WriteLine(" ***  Birthplace: Seoul, South Korea       ***");
                    Console.WriteLine(" ***  Height: 160 cm (5'3)                 ***");
                    Console.WriteLine(" ***  Weight: 46 kg (101 lbs)              ***");
                    Console.WriteLine(" ***  Blood Type: A                        ***");
                    Console.WriteLine(" ***  Position: Leader, Main Dancer,       ***");
                    Console.WriteLine(" ***    Lead Vocalist                      ***");
                    Console.WriteLine(" ***  Produce 48 final ranking: 7          ***");
                    Console.WriteLine(" ***  Official Color: Purple               ***");
                    Console.WriteLine(" ***  Likes: Green tea/Choco ice cream     ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    break;
                case "8":
                    Console.WriteLine("                                             ");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***              Kang Hyewon              ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***  Stage Name: Hyewon                   ***");
                    Console.WriteLine(" ***  Birthday: July 5, 1999               ***");
                    Console.WriteLine(" ***  Zodiac Sign: Cancer                  ***");
                    Console.WriteLine(" ***  Birthplace: Yangsan,                 ***");
                    Console.WriteLine(" ***    South Gyeongsang , South Korea     ***");
                    Console.WriteLine(" ***  Height: 163 cm (5'4)                 ***");
                    Console.WriteLine(" ***  Weight: 43 kg (95 lbs)               ***");
                    Console.WriteLine(" ***  Blood Type: B                        ***");
                    Console.WriteLine(" ***  Position: Lead Rapper, Visual,       ***");
                    Console.WriteLine(" ***    Sub Vocalist                       ***");
                    Console.WriteLine(" ***  Produce 48 final ranking: 8          ***");
                    Console.WriteLine(" ***  Official Color: Coral                ***");
                    Console.WriteLine(" ***  Likes: Vanilla ice cream and anime   ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    break;
                case "9":
                    Console.WriteLine("                                             ");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***             Honda Hitomi              ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***  Stage Name: Hitomi                   ***");
                    Console.WriteLine(" ***  Birthday: October 6, 2001            ***");
                    Console.WriteLine(" ***  Zodiac Sign: Libra                   ***");
                    Console.WriteLine(" ***  Birthplace: Tochigi, Japan           ***");
                    Console.WriteLine(" ***  Height: 158 cm (5'2)                 ***");
                    Console.WriteLine(" ***  Weight: 44.4 kg (98 lbs)             ***");
                    Console.WriteLine(" ***  Blood Type: A                        ***");
                    Console.WriteLine(" ***  Position: Sub Rapper, Lead Dancer,   ***");
                    Console.WriteLine(" ***    Sub Vocalist                       ***");
                    Console.WriteLine(" ***  Produce 48 final ranking: 9          ***");
                    Console.WriteLine(" ***  Official Color: Peach                ***");
                    Console.WriteLine(" ***  Likes: Strawberries and gyoza        ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    break;
                case "10":
                    Console.WriteLine("                                             ");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***             Kim Chaewon               ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***  Stage Name: Chaewon                  ***");
                    Console.WriteLine(" ***  Birthday: August 1, 2000             ***");
                    Console.WriteLine(" ***  Zodiac Sign: Leo                     ***");
                    Console.WriteLine(" ***  Birthplace: Seoul, South Korea       ***");
                    Console.WriteLine(" ***  Height: 163 cm (5'3)                 ***");
                    Console.WriteLine(" ***  Weight: 42 kg (92 lbs)               ***");
                    Console.WriteLine(" ***  Blood Type: B                        ***");
                    Console.WriteLine(" ***  Position: Lead Vocalist, Lead Dancer ***");
                    Console.WriteLine(" ***  Produce 48 final ranking: 10         ***");
                    Console.WriteLine(" ***  Official Color: Mint                 ***");
                    Console.WriteLine(" ***  Likes: Mint chocolate ice cream      ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    break;
                case "11":
                    Console.WriteLine("                                             ");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***              Kim Minju                ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***  Stage Name: Minju                    ***");
                    Console.WriteLine(" ***  Birthday: February 5, 2001           ***");
                    Console.WriteLine(" ***  Zodiac Sign: Aquarius                ***");
                    Console.WriteLine(" ***  Birthplace: Seoul, South Korea       ***");
                    Console.WriteLine(" ***  Height: 163.8 cm (5'4)               ***");
                    Console.WriteLine(" ***  Weight: 45 kg (99 lbs)               ***");
                    Console.WriteLine(" ***  Blood Type: AB                       ***");
                    Console.WriteLine(" ***  Position: Lead Rapper, Visual,       ***");
                    Console.WriteLine(" ***    Sub Vocalist                       ***");
                    Console.WriteLine(" ***  Produce 48 final ranking: 11         ***");
                    Console.WriteLine(" ***  Official Color: White                ***");
                    Console.WriteLine(" ***  Likes: Chocolate ice cream           ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    break;
                case "12":
                    Console.WriteLine("                                             ");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***              Lee Chaeyeon             ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***  Stage Name: Chaeyeon                 ***");
                    Console.WriteLine(" ***  Birthday: January 11, 2000           ***");
                    Console.WriteLine(" ***  Zodiac Sign: Capricorn               ***");
                    Console.WriteLine(" ***  Birthplace: Yongin, South Korea      ***");
                    Console.WriteLine(" ***  Height: 165 cm (5'5)                 ***");
                    Console.WriteLine(" ***  Weight: 47 kg (104 lbs)              ***");
                    Console.WriteLine(" ***  Blood Type: A                        ***");
                    Console.WriteLine(" ***  Position: Main Dancer, Lead Rapper,  ***");
                    Console.WriteLine(" ***    Lead Vocalist                      ***");
                    Console.WriteLine(" ***  Produce 48 final ranking: 12         ***");
                    Console.WriteLine(" ***  Official Color: Blue Mint            ***");
                    Console.WriteLine(" ***  Likes: Yogurt ice cream              ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    break;
                default:
                    Console.WriteLine("                                             ");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***             ERROR: IZ*GONE            ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" ***                                       ***");
                    Console.WriteLine(" *********************************************");
                    Console.WriteLine(" *********************************************");
                    break;
            }

            Console.ReadKey();
        }
    }
}
